name: E2E test Chrome Headless
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: "http://localhost:4200"
          browser: chrome
          headless: true

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cy-screenshots
          path: cy-screenshots

      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cy-videos
          path: cy-videos
